name: clean_deployment_env

on:
  # Run weekly, at 00:00 on sunday.
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
 cleanup:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Delete deployment
        uses: strumwolf/delete-deployment-environment@v2.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: github-pages
          onlyRemoveDeployments: true